### ISSUE TITLE
Colcon depends on CMake 3.10.2 on Ubuntu 18.04 

### ISSUE THREAD

**Issue by ar0usel** [colcon/colcon-cmake#101]
When I'm installing **python3-colcon-cmake** package it changes CMake to 3.10.2. There are any opportunities to install it with CMake 3.13 or higher?

**Comment by christophebedard** [comment]
`colcon-cmake` doesn't explicitly specify a cmake version: https://github.com/colcon/colcon-cmake/blob/50b845a182916a0b5595480087b71559ee2014db/stdeb.cfg#L3. And it seems to be able to work with any version: https://github.com/colcon/colcon-cmake/blob/50b845a182916a0b5595480087b71559ee2014db/colcon_cmake/task/cmake/build.py#L326-L339

3.10.2 is simply the version available from apt on 18.04: https://packages.ubuntu.com/bionic/cmake

**Comment by ar0usel** [comment]
Thank you! It is helped me.
