### ISSUE TITLE
PRs failing on flake8 `DeprecationWarning: SelectableGroups`

### ISSUE THREAD

**Issue by KazNX** [colcon/colcon-cmake#108]
Hi,

I'm getting the following deprecation warning from flake8 which is failing some PRs I've put up

> DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
> [snip]
> FAILED test/test_flake8.py::test_flake8 - DeprecationWarning: SelectableGroup...

As far as I can tell, this is not to do with my changes. I'd infer that something has changed in flake8 and the flake8 validation script needs to be updated.

I've successfully run the `test_flake8` script locally with Python 3.8 and flake8 3.9.2.

Please advise. Thanks.

**Comment by dirk-thomas** [comment]
The referenced PR fixed the unrelated CI failures. Please rebase your PR to hopefully pass CI.

**Comment by KazNX** [comment]
Thanks. Seems to have done the trick. I've rebased the PRs and they are now passing the CI checks.
