### ISSUE TITLE
Unable to generate compile_commands.json on Windows

### ISSUE THREAD

**Issue by Scotty1701** [colcon/colcon-cmake#115]
I'm attempting to generate a `compile_commands.json` file for use with `clangd`, however the file is not generated (neither on a package level nor the workspace level). Attempting to build the `turtlesim` package from `ros_tutorials` with
```
PS D:\Documents\dev_ws> colcon build --merge-install --event-handlers console_cohesion+ --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```
gives the following warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_COMPILE_COMMANDS
```

My platform is Windows 10 with Ros2 Foxy installed from the aka.ms/ros Chocolatey package.

I build colcon from source following the instructions in the [docs](https://colcon.readthedocs.io/en/released/developer/bootstrap.html), and `colcon version-check` gives:
```
colcon-cd 0.1.1: up-to-date
colcon-cmake 0.2.26: up-to-date
colcon-core 0.7.1: up-to-date
colcon-defaults 0.2.6: up-to-date
colcon-devtools 0.2.3: up-to-date
colcon-library-path 0.2.1: up-to-date
colcon-metadata 0.2.5: up-to-date
colcon-mixin 0.2.1: up-to-date
colcon-notification 0.2.13: up-to-date
colcon-output 0.2.12: up-to-date
colcon-package-information 0.3.3: up-to-date
colcon-package-selection 0.2.10: up-to-date
colcon-parallel-executor 0.2.4: up-to-date
colcon-pkg-config 0.1.0: up-to-date
colcon-powershell 0.3.7: up-to-date
colcon-python-setup-py 0.2.7: up-to-date
colcon-recursive-crawl 0.2.1: up-to-date
colcon-ros 0.3.22: up-to-date
colcon-test-result 0.3.8: up-to-date
colcon-zsh 0.4.0: up-to-date
```
Attempting the same in an Ubuntu 20.04 with identical colcon versions correctly generates `compile_commands.json` on a package and workspace level. 

I also tested on windows with the change proposed in #114, however this did not result in any changed behavior. Additionally, I tested ommitting the `--merge-install` option, which produced no change for either platform.

**Comment by Scotty1701** [comment]
This CMake flag is only implemented for Makefile Generators and Ninja (https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html). Ninja is supported on Windows, so I recommend using that instead of the default generator.

**Comment by quetalasj** [comment]
I have the same issue on ubuntu 22.04 with ROS2.

Commands:

`colcon build --cmake-args -D CMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja`

or just

`colcon build --cmake-args -D CMAKE_EXPORT_COMPILE_COMMANDS=ON`

returns:

`CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_COMPILE_COMMANDS`

colcon version-check result:


`/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
colcon-argcomplete 0.3.3: up-to-date
colcon-bash 0.4.2: up-to-date
colcon-cd 0.1.1: up-to-date
colcon-cmake 0.2.27: up-to-date
colcon-core 0.12.1: up-to-date
colcon-defaults 0.2.8: up-to-date
colcon-devtools 0.2.3: up-to-date
colcon-installed-package-information 0.1.0: up-to-date
colcon-library-path 0.2.1: up-to-date
colcon-metadata 0.2.5: up-to-date
colcon-notification 0.2.15: up-to-date
colcon-output 0.2.13: up-to-date
colcon-override-check 0.0.1: up-to-date
colcon-package-information 0.3.3: up-to-date
colcon-package-selection 0.2.10: up-to-date
colcon-parallel-executor 0.2.4: up-to-date
colcon-pkg-config 0.1.0: up-to-date
colcon-powershell 0.3.7: up-to-date
colcon-python-setup-py 0.2.8: up-to-date
colcon-recursive-crawl 0.2.1: up-to-date
colcon-ros 0.3.23: up-to-date
colcon-test-result 0.3.8: up-to-date
colcon-zsh 0.4.0: up-to-date`
