### ISSUE TITLE
colcon-build for a cmake project doesn't pickup CMAKE_ vars from the environment

### ISSUE THREAD

**Issue by jfinken** [colcon/colcon-cmake#132]
The below describes a reduction exhibiting the symptom:

- ROS2-Humble-Desktop docker image from OSRF (`osrf/ros:humble-desktop)`:
```bash
$ printenv | grep ROS
ROS_VERSION=2
ROS_PYTHON_VERSION=3
ROS_LOCALHOST_ONLY=0
ROS_DISTRO=humble
```
- created a ROS2 package via `ros2 pkg create --build-type ament_cmake <package_name>`
- Export, for example, these variables within the environment.  Crucially in my case, `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` are exported by a pre-colcon-build step involving conan.
```bash
export CMAKE_C_FLAGS="foo"
export CMAKE_CXX_FLAGS="bar; baz"
```
- In the `CMakeLists.txt`, print out `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS`:
```bash
message("CMAKE_C_FLAGS are:   ${CMAKE_C_FLAGS}")
message("CMAKE_CXX_FLAGS are: ${CMAKE_CXX_FLAGS}")
```
- During a clean `colcon build`, those variables are empty:
```bash
$ colcon build
...
CMAKE_C_FLAGS are:    
CMAKE_CXX_FLAGS are: 
```

The solution is to force the set in `CMakeLists.txt`.  But why?
```bash
set(CMAKE_C_FLAGS "$ENV{CMAKE_C_FLAGS} $ENV{CFLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "$ENV{CMAKE_CXX_FLAGS} $ENV{CXXFLAGS}" CACHE STRING "" FORCE)
```
```bash
$ colcon build
...
CMAKE_C_FLAGS are:   foo 
CMAKE_CXX_FLAGS are: foo; bar; baz
```

**Comment by cottsay** [comment]
I can't find any evidence that `CMAKE_<LANG>_FLAGS` is expected to take it's value from an environment variable with the same name. In fact, the documentation specifically says that `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` takes their initial value from the `CFLAGS` and `CXXFLAGS` environment variables respectively.

When I use the proper environment variables, this seems to work as expected. Also, I can reproduce the behavior you described here outside of colcon by simply invoking cmake directly on the project, so I don't see how this could be a problem in colcon itself.

**Comment by cottsay** [comment]
@jfinken, do you still believe there is a problem with colcon's behavior here, or can this ticket be closed?

**Comment by jfinken** [comment]
> @jfinken, do you still believe there is a problem with colcon's behavior here, or can this ticket be closed?

My apologies.  Yes this ticket can be closed.  Thank you.
