### ISSUE TITLE
CTest result files are not in --test-result-base

### ISSUE THREAD

**Issue by cottsay** [colcon/colcon-cmake#79]
Example:
```
colcon build --test-result-base test_results
colcon test --test-result-base test_results
colcon test-result --test-result-base test_results --all --result-files-only
```
Expected behavior would be that the CTest `Test.xml` results from any ctest invocations would be printed. However, those files ended up in the `--build-base`. This seems to contradict the explicit purpose of `--test-result-base`, "the base path for all test results".

From the example above, if you run `colcon test-result --all --result-files-only` so that `--test-result-base` defaults to be the same as `--build-base`, the paths to the CTest `Test.xml` results are printed as expected.

**Comment by dirk-thomas** [comment]
I am not aware of any way to instruct `ctest` to place the generated files into a different folder than the build dir. If there is no such option we could copy / symlink th files after the tests finished.

**Comment by Aposhian** [comment]
The merged PR copies the CTest result Test.xml, but does not copy *xunit.xml files over. This is confusing, since the documentation says that `--test-result-base` specifies "The base path for all test results."
