### ISSUE TITLE
Workspace-level "compile_commands.json" is being generated by "colcon test"

### ISSUE THREAD

**Issue by mm318** [colcon/colcon-cmake#81]
It looks like the new `CompileCommandsEventHandler` (introduced by https://github.com/colcon/colcon-cmake/pull/69) is being invoked by `colcon test`.

For example, if you do
```
colcon build --event-handlers compile_commands- --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
colcon test  # don't specify any --event-handlers options
```
there will still end up being a workspace-level `compile_commands.json` under `build/`.

Is this intended behavior? I think it's more intuitive if the workspace-level`compile_commands.json` is only generated during `colcon build`.

**Comment by dirk-thomas** [comment]
> I think it's more intuitive if the workspace-level `compile_commands.json` is only generated during `colcon build`.

I agrees that regenerating the file is only necessary during `build` but not `test`. Unfortunately the event handlers have no way to determine what verb was used and there is no event type which would distinguish a `build` from a `test` at the moment.
