### ISSUE TITLE
compile_commands.json and CLion

### ISSUE THREAD

**Issue by stevemartinov** [colcon/colcon-cmake#87]
Hi, does anyone know how can I use the `compile_commands.json` in CLion when using ROS2?

**Comment by christophebedard** [comment]
I've never tried it, but this seems to be what you're looking for: https://www.jetbrains.com/help/clion/compilation-database.html#compdb_clion

**Comment by dirk-thomas** [comment]
@stevemartinov If the previous comment answered your question please go ahead and close this ticket.

**Comment by stevemartinov** [comment]
Yes, thank you.
